### ISSUE TITLE
base64 decoding issues

### ISSUE THREAD

**Issue by kjans123** [kjans123/ImageProcessorS18#54]
https://github.com/kjans123/ImageProcessorS18/blob/bc160554f1a74233c009d224a7c4da0df149c71e/server/ProcessServer.py#L106-L133

https://github.com/kjans123/ImageProcessorS18/blob/eb2f19d0dbe12c9d9b350e5c92eb1bbdd9f96dda/server/base64_conv_numpy.py#L74-L91

https://github.com/kjans123/ImageProcessorS18/blob/e0e404ccd428c20af1d0dcd5d08e002a36aa393d/frontend/src/App.js#L136-L154

the image.open('temp.JPG') line keeps bugging. we think this is due to a corrupted base64 string or to some conflict between flask and PIL

@suyashkumar

**Comment by suyashkumar** [comment]
@kjans123 so this only fails when running on the VCM and works fine locally? Are you able to view temp.JPG in an image viewer? You should be able to use scp to pull the file over. Let's chat further tomorrow on this.

**Comment by kjans123** [comment]
successfully figured out why this was bugging
