### ISSUE TITLE
base64_conv_numpy.py buggy code

### ISSUE THREAD

**Issue by kjans123** [kjans123/ImageProcessorS18#8]
Having issues converting png image to base64 string, running hist_equal package from scikit-image on it and then reconverting back to a base64 string to send back to front-end. After decoding processed base64 string, the png image is not viewable and its size is increased approximately 10X.

**Comment by kjans123** [comment]
@mlp6

**Comment by kjans123** [comment]
I think this is linking the lines:

https://github.com/kjans123/ImageProcessorS18/blob/5e68ef7794adb2140e3bd799808b7c5747094922/base64_conv_numpy.py#L14-L22

**Comment by mlp6** [comment]
`base64image` is a "serialized" string of `base64` data from you image file.  If you were to simply decode and write that, you would just get your original file (the PNG file) back.  Once you convert the data to an image array, you *cannot* simply write those data back out.  Doing the serial encode/decode operations on Lines 19-20 do not "undo" this image array conversion.

**Comment by kjans123** [comment]
Alright, so, assuming I'm doing everything correctly up until lines 19-20, I have a numpy image array that has been processed. Is there a way to convert it back into base64 string and/or into a viewable picture?

**Comment by kjans123** [comment]
So, I can at least get this work:
https://github.com/kjans123/ImageProcessorS18/blob/23a013770166cb6db650544a261ac877b0e528d3/base64_conv_numpy.py#L18-L31

**Comment by kjans123** [comment]
https://github.com/kjans123/ImageProcessorS18/blob/139e957ed086997bef24633bf294e6772d9d0bce/base64_conv_numpy.py#L1-L138

**Comment by kjans123** [comment]
Issues has been resolved. Successfully converted image to base64, to image array and back to base64
