### ISSUE TITLE
Reverse Video and Log Compression Definitions

### ISSUE THREAD

**Issue by ML273** [kjans123/ImageProcessorS18#9]
Hello, Dr. Palmeri @mlp6 

I have created an issue highlighting my ignorance as to what Reverse Video refers to. Some references on this would be appreciated.

As for log compression, in a previous class, there was a method of just using the log function in MATLAB on the image (to decrease the scale and increase low intensity pixels). Is this the same thing for the project? 

Thank you,

Marianne

**Comment by mlp6** [comment]
I think/hope that my Slack comments answered this!

One thing to be aware of is how the `log()` function will handle pixel values = 0.
